<a href="https://colab.research.google.com/github/muhammadshoaib549/pytorch/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

2.10.0+cu128
GPU is available!
Using GPU: Tesla T4


In [ ]:
#this is for the Empty
a=torch.empty(2,3)
print(a)


tensor([[2.1715e-18, 2.3081e-12, 2.6302e+20],
        [6.1943e-04, 3.6022e-12, 6.9989e+22]])


In [ ]:
#Checking the Type
type (a)


torch.Tensor

In [ ]:
#this is for the Ones
torch.ones(2,3)


tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#this is for the Random Values
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [ ]:
# manual Seed
torch.manual_seed(100)
random_tensor = torch.rand(2, 3)
print(random_tensor)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


In [ ]:
#this is for the Tensor
# Fixed version
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# 4. Range and Distribution Functions
print("--- Specialized Initializers ---")

# arange: (start, end, step) -> excludes end
print("Using arange  ->", torch.arange(0, 10, 2))

# linspace: (start, end, steps) -> includes end
print("Using linspace ->", torch.linspace(0, 10, 10))

# eye: Identity Matrix (diagonal of 1s)
print("Using eye      ->\n", torch.eye(5))

# full: (shape, value) -> fills everything with the value
print("Using full     ->\n", torch.full((3, 3), 5))

--- Specialized Initializers ---
Using arange  -> tensor([0, 2, 4, 6, 8])
Using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eye      ->
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full     ->
 tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [ ]:
# Define x first
x = torch.tensor([[1, 2, 3], [4, 5, 6],[1,4,5]])

# Then run your checks
print(f"Shape: {x.shape}")
print(f"Rank (ndim): {x.ndim}")
print(f"Total elements: {x.numel()}")
print(f"Data type: {x.dtype}")
print(f"Device: {x.device}")


Shape: torch.Size([3, 3])
Rank (ndim): 2
Total elements: 9
Data type: torch.int64
Device: cpu


In [ ]:
#this is for the zero likes
torch.zeros_like(x)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [ ]:
#this is fr the ones like
torch.ones_like(x)


tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [ ]:
# Create a starting tensor
x = torch.tensor([[1, 0, 3], [4, 5, 6]], dtype=torch.int32)
#You are telling Python to take the string "-" and repeat it 30 times.
print(f"Original Tensor:\n{x}\n" + "-"*30)

# --- FLOATING POINT TYPES ---
# Standard for DL (float32), high precision (float64), and half-precision (float16/bfloat16)
x_f32 = x.to(torch.float32)
x_f64 = x.to(torch.float64)
x_f16 = x.to(torch.float16)
x_bf16 = x.to(torch.bfloat16)

# --- INTEGER TYPES ---
# 8-bit to 64-bit signed integers
x_i8 = x.to(torch.int8)
x_i16 = x.to(torch.int16)
x_i32 = x.to(torch.int32)
x_i64 = x.to(torch.int64)

# Unsigned 8-bit (commonly used for images)
x_uint8 = x.to(torch.uint8)

# --- BOOLEAN & COMPLEX ---
x_bool = x.to(torch.bool)        # 0 becomes False, non-zero becomes True
x_c64 = x.to(torch.complex64)    # Real numbers become the 'real' part of the complex num

# --- PRINTING THE RESULTS ---
types_to_show = [
    ("32-bit Float", x_f32),
    ("64-bit Float", x_f64),
    ("16-bit Float", x_f16),
    ("BFloat16", x_bf16),
    ("8-bit Int", x_i8),
    ("32-bit Int", x_i32),
    ("64-bit Int", x_i64),
    ("Unsigned Int8", x_uint8),
    ("Boolean", x_bool),
    ("Complex 64", x_c64)
]

for name, tensor in types_to_show:
    print(f"{name:15} | Dtype: {str(tensor.dtype):18} | Example Value: {tensor[0,0]}")

Original Tensor:
tensor([[1, 0, 3],
        [4, 5, 6]], dtype=torch.int32)
------------------------------
32-bit Float    | Dtype: torch.float32      | Example Value: 1.0
64-bit Float    | Dtype: torch.float64      | Example Value: 1.0
16-bit Float    | Dtype: torch.float16      | Example Value: 1.0
BFloat16        | Dtype: torch.bfloat16     | Example Value: 1.0
8-bit Int       | Dtype: torch.int8         | Example Value: 1
32-bit Int      | Dtype: torch.int32        | Example Value: 1
64-bit Int      | Dtype: torch.int64        | Example Value: 1
Unsigned Int8   | Dtype: torch.uint8        | Example Value: 1
Boolean         | Dtype: torch.bool         | Example Value: True
Complex 64      | Dtype: torch.complex64    | Example Value: (1+0j)


In [ ]:
# This is the line for the Generating Random Tensor Just matching like the X one

random_tensor = torch.rand_like(x, dtype=torch.float32)

print("Random Tensor (same shape as x):")
print(random_tensor)
print(f"New Dtype: {random_tensor.dtype}")

Random Tensor (same shape as x):
tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])
New Dtype: torch.float32


Mathematical OPerations

In [ ]:
import torch

# Create a random 2x2 tensor
x = torch.rand(2, 2)
print(f"Original x:\n{x}\n")

# --- Math Operations ---

# addition
print(f"Addition (x + 10):\n{x + 10}")

# substraction
print(f"Subtraction (x - 5):\n{x - 5}")

# multiplication
print(f"Multiplication (x * 2):\n{x * 2}")

# division
print(f"Division (x / 2):\n{x / 2}")

# int division (floor division)
print(f"Int Division (x // 0.5):\n{x // 0.5}")

# --- Power and Modulo ---

# Power (Exponentiation)
# Use ** to raise x to a power (e.g., x squared)
power_res = x ** 2
print(f"Power (x^2):\n{power_res}")

# Modulo (Remainder) logic from your snippet
# (x // 0.5) calculates how many 0.5s fit in x, then % 2 checks if that count is even/odd
logic_gate = (x // 0.5) % 2
print(f"Logic Gate ((x // 0.5) % 2):\n{logic_gate}")

Original x:
tensor([[0.9535, 0.7064],
        [0.1629, 0.8902]])

Addition (x + 10):
tensor([[10.9535, 10.7064],
        [10.1629, 10.8902]])
Subtraction (x - 5):
tensor([[-4.0465, -4.2936],
        [-4.8371, -4.1098]])
Multiplication (x * 2):
tensor([[1.9071, 1.4128],
        [0.3258, 1.7804]])
Division (x / 2):
tensor([[0.4768, 0.3532],
        [0.0814, 0.4451]])
Int Division (x // 0.5):
tensor([[1., 1.],
        [0., 1.]])
Power (x^2):
tensor([[0.9092, 0.4990],
        [0.0265, 0.7925]])
Logic Gate ((x // 0.5) % 2):
tensor([[1., 1.],
        [0., 1.]])


ElementWise


In [ ]:
# Create two random tensors of the same shape (2x3)
a = torch.rand(2, 3)
b = torch.rand(2, 3)

print("Tensor a:")
print(a)
print("\nTensor b:")
print(b)
print("-" * 30)

# 1. add
# Adds each element of a to the corresponding element of b
add_res = a + b
# Or: torch.add(a, b)

# 2. sub
# Subtracts b from a element-wise
sub_res = a - b
# Or: torch.sub(a, b)

# 3. multiply
# This is Hadamard Product (NOT matrix multiplication)
# It multiplies 0.0554 * 0.3466, etc.
mult_res = a * b
# Or: torch.mul(a, b)

# 4. division
# Divides a by b element-wise
div_res = a / b
# Or: torch.div(a, b)

# Display results
print(f"Addition Result:\n{add_res}")
print(f"Sub\n{sub_res}")
print(f"Devision\n{div_res}")
print(f"Multiplication Result:\n{mult_res}")

Tensor a:
tensor([[0.6017, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])

Tensor b:
tensor([[0.3079, 0.6269, 0.8277],
        [0.6594, 0.0887, 0.4890]])
------------------------------
Addition Result:
tensor([[0.9096, 1.0504, 1.3501],
        [1.0769, 0.1227, 1.4047]])
Sub
tensor([[ 0.2938, -0.2035, -0.3052],
        [-0.2418, -0.0547,  0.4268]])
Devision
tensor([[1.9541, 0.6754, 0.6312],
        [0.6332, 0.3834, 1.8728]])
Multiplication Result:
tensor([[0.1852, 0.2655, 0.4324],
        [0.2753, 0.0030, 0.4478]])


Video from 41 Some Operaations on the Single Tensor

In [4]:
c=torch.tensor([1,-2,3,-4])

In [5]:
#Absolute value
torch.abs(c)


tensor([1, 2, 3, 4])

In [6]:
#Convering to the Negative from the zero
torch.neg(c)


tensor([-1,  2, -3,  4])

In [7]:
#Rounding
torch.round(c)


tensor([ 1, -2,  3, -4])