<a href="https://colab.research.google.com/github/muhammadshoaib549/pytorch/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

2.10.0+cpu
GPU not available. Using CPU.


In [ ]:
#this is for the Empty
a=torch.empty(2,3)
print(a)


tensor([[2.1715e-18, 2.3081e-12, 2.6302e+20],
        [6.1943e-04, 3.6022e-12, 6.9989e+22]])


In [ ]:
#Checking the Type
type (a)


torch.Tensor

In [ ]:
#this is for the Ones
torch.ones(2,3)


tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#this is for the Random Values
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [ ]:
# manual Seed
torch.manual_seed(100)
random_tensor = torch.rand(2, 3)
print(random_tensor)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


In [ ]:
#this is for the Tensor
# Fixed version
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# 4. Range and Distribution Functions
print("--- Specialized Initializers ---")

# arange: (start, end, step) -> excludes end
print("Using arange  ->", torch.arange(0, 10, 2))

# linspace: (start, end, steps) -> includes end
print("Using linspace ->", torch.linspace(0, 10, 10))

# eye: Identity Matrix (diagonal of 1s)
print("Using eye      ->\n", torch.eye(5))

# full: (shape, value) -> fills everything with the value
print("Using full     ->\n", torch.full((3, 3), 5))

--- Specialized Initializers ---
Using arange  -> tensor([0, 2, 4, 6, 8])
Using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eye      ->
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full     ->
 tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [ ]:
# Define x first
x = torch.tensor([[1, 2, 3], [4, 5, 6],[1,4,5]])

# Then run your checks
print(f"Shape: {x.shape}")
print(f"Rank (ndim): {x.ndim}")
print(f"Total elements: {x.numel()}")
print(f"Data type: {x.dtype}")
print(f"Device: {x.device}")


Shape: torch.Size([3, 3])
Rank (ndim): 2
Total elements: 9
Data type: torch.int64
Device: cpu


In [ ]:
#this is for the zero likes
torch.zeros_like(x)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [ ]:
#this is fr the ones like
torch.ones_like(x)


tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [ ]:
# Create a starting tensor
x = torch.tensor([[1, 0, 3], [4, 5, 6]], dtype=torch.int32)
#You are telling Python to take the string "-" and repeat it 30 times.
print(f"Original Tensor:\n{x}\n" + "-"*30)

# --- FLOATING POINT TYPES ---
# Standard for DL (float32), high precision (float64), and half-precision (float16/bfloat16)
x_f32 = x.to(torch.float32)
x_f64 = x.to(torch.float64)
x_f16 = x.to(torch.float16)
x_bf16 = x.to(torch.bfloat16)

# --- INTEGER TYPES ---
# 8-bit to 64-bit signed integers
x_i8 = x.to(torch.int8)
x_i16 = x.to(torch.int16)
x_i32 = x.to(torch.int32)
x_i64 = x.to(torch.int64)

# Unsigned 8-bit (commonly used for images)
x_uint8 = x.to(torch.uint8)

# --- BOOLEAN & COMPLEX ---
x_bool = x.to(torch.bool)        # 0 becomes False, non-zero becomes True
x_c64 = x.to(torch.complex64)    # Real numbers become the 'real' part of the complex num

# --- PRINTING THE RESULTS ---
types_to_show = [
    ("32-bit Float", x_f32),
    ("64-bit Float", x_f64),
    ("16-bit Float", x_f16),
    ("BFloat16", x_bf16),
    ("8-bit Int", x_i8),
    ("32-bit Int", x_i32),
    ("64-bit Int", x_i64),
    ("Unsigned Int8", x_uint8),
    ("Boolean", x_bool),
    ("Complex 64", x_c64)
]

for name, tensor in types_to_show:
    print(f"{name:15} | Dtype: {str(tensor.dtype):18} | Example Value: {tensor[0,0]}")

Original Tensor:
tensor([[1, 0, 3],
        [4, 5, 6]], dtype=torch.int32)
------------------------------
32-bit Float    | Dtype: torch.float32      | Example Value: 1.0
64-bit Float    | Dtype: torch.float64      | Example Value: 1.0
16-bit Float    | Dtype: torch.float16      | Example Value: 1.0
BFloat16        | Dtype: torch.bfloat16     | Example Value: 1.0
8-bit Int       | Dtype: torch.int8         | Example Value: 1
32-bit Int      | Dtype: torch.int32        | Example Value: 1
64-bit Int      | Dtype: torch.int64        | Example Value: 1
Unsigned Int8   | Dtype: torch.uint8        | Example Value: 1
Boolean         | Dtype: torch.bool         | Example Value: True
Complex 64      | Dtype: torch.complex64    | Example Value: (1+0j)


In [ ]:
# This is the line for the Generating Random Tensor Just matching like the X one

random_tensor = torch.rand_like(x, dtype=torch.float32)

print("Random Tensor (same shape as x):")
print(random_tensor)
print(f"New Dtype: {random_tensor.dtype}")

Random Tensor (same shape as x):
tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])
New Dtype: torch.float32


Mathematical OPerations

In [ ]:
import torch

# Create a random 2x2 tensor
x = torch.rand(2, 2)
print(f"Original x:\n{x}\n")

# --- Math Operations ---

# addition
print(f"Addition (x + 10):\n{x + 10}")

# substraction
print(f"Subtraction (x - 5):\n{x - 5}")

# multiplication
print(f"Multiplication (x * 2):\n{x * 2}")

# division
print(f"Division (x / 2):\n{x / 2}")

# int division (floor division)
print(f"Int Division (x // 0.5):\n{x // 0.5}")

# --- Power and Modulo ---

# Power (Exponentiation)
# Use ** to raise x to a power (e.g., x squared)
power_res = x ** 2
print(f"Power (x^2):\n{power_res}")

# Modulo (Remainder) logic from your snippet
# (x // 0.5) calculates how many 0.5s fit in x, then % 2 checks if that count is even/odd
logic_gate = (x // 0.5) % 2
print(f"Logic Gate ((x // 0.5) % 2):\n{logic_gate}")

Original x:
tensor([[0.9535, 0.7064],
        [0.1629, 0.8902]])

Addition (x + 10):
tensor([[10.9535, 10.7064],
        [10.1629, 10.8902]])
Subtraction (x - 5):
tensor([[-4.0465, -4.2936],
        [-4.8371, -4.1098]])
Multiplication (x * 2):
tensor([[1.9071, 1.4128],
        [0.3258, 1.7804]])
Division (x / 2):
tensor([[0.4768, 0.3532],
        [0.0814, 0.4451]])
Int Division (x // 0.5):
tensor([[1., 1.],
        [0., 1.]])
Power (x^2):
tensor([[0.9092, 0.4990],
        [0.0265, 0.7925]])
Logic Gate ((x // 0.5) % 2):
tensor([[1., 1.],
        [0., 1.]])


ElementWise


In [ ]:
# Create two random tensors of the same shape (2x3)
a = torch.rand(2, 3)
b = torch.rand(2, 3)

print("Tensor a:")
print(a)
print("\nTensor b:")
print(b)
print("-" * 30)

# 1. add
# Adds each element of a to the corresponding element of b
add_res = a + b
# Or: torch.add(a, b)

# 2. sub
# Subtracts b from a element-wise
sub_res = a - b
# Or: torch.sub(a, b)

# 3. multiply
# This is Hadamard Product (NOT matrix multiplication)
# It multiplies 0.0554 * 0.3466, etc.
mult_res = a * b
# Or: torch.mul(a, b)

# 4. division
# Divides a by b element-wise
div_res = a / b
# Or: torch.div(a, b)

# Display results
print(f"Addition Result:\n{add_res}")
print(f"Sub\n{sub_res}")
print(f"Devision\n{div_res}")
print(f"Multiplication Result:\n{mult_res}")

Tensor a:
tensor([[0.6017, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])

Tensor b:
tensor([[0.3079, 0.6269, 0.8277],
        [0.6594, 0.0887, 0.4890]])
------------------------------
Addition Result:
tensor([[0.9096, 1.0504, 1.3501],
        [1.0769, 0.1227, 1.4047]])
Sub
tensor([[ 0.2938, -0.2035, -0.3052],
        [-0.2418, -0.0547,  0.4268]])
Devision
tensor([[1.9541, 0.6754, 0.6312],
        [0.6332, 0.3834, 1.8728]])
Multiplication Result:
tensor([[0.1852, 0.2655, 0.4324],
        [0.2753, 0.0030, 0.4478]])


Video from 41 Some Operaations on the Single Tensor

In [ ]:
c=torch.tensor([1,-2,3,-4])

In [ ]:
#Absolute value
torch.abs(c)


tensor([1, 2, 3, 4])

In [ ]:
#Convering to the Negative from the zero
torch.neg(c)


tensor([-1,  2, -3,  4])

In [ ]:
#Rounding
torch.round(c)


tensor([ 1, -2,  3, -4])

Lets Leran About the Tensor Operations


In [ ]:

# 1. Generate ONE random tensor (3x3)
# We multiply by 10 to make the floor/ceil/clamp operations more visible
x = torch.rand(3, 3) * 10
print(f"--- The Random Tensor ---\n{x}\n")


--- The Random Tensor ---
tensor([[7.3380, 8.7319, 2.7055],
        [4.8770, 8.3481, 8.8727],
        [0.0820, 6.6114, 6.6545]])



Lets Learn ABut the Some of the Reduce FUnctins


FLoor Fuction

In [ ]:
# --- 1. ROUNDING OPERATIONS ---
# floor: Removes the decimal and rounds DOWN (e.g., 3.9 becomes 3)
print(f"Floor (Round Down): \n{torch.floor(x)}")

Floor (Round Down): 
tensor([[7., 8., 2.],
        [4., 8., 8.],
        [0., 6., 6.]])


Learning about the CELL


In [ ]:

# ceil: Rounds UP to the next integer (e.g., 3.1 becomes 4)
print(f"Ceil (Round Up): \n{torch.ceil(x)}")

Ceil (Round Up): 
tensor([[8., 9., 3.],
        [5., 9., 9.],
        [1., 7., 7.]])


Lets Learn ABout the Clamp


In [ ]:
# clamp: Limits values to a range.
# Anything smaller than 'min' becomes 'min'. Anything larger than 'max' becomes 'max'.
print(f"Clamp (Forcing values between 3.0 and 7.0): \n{torch.clamp(x, 3.0, 7.0)}\n")

Clamp (Forcing values between 3.0 and 7.0): 
tensor([[7.0000, 7.0000, 3.0000],
        [4.8770, 7.0000, 7.0000],
        [3.0000, 6.6114, 6.6545]])



FInding the SUm of the Matix ANd the Dimension WIse


In [ ]:
# --- 1. SUM (Addition) ---
print(f"Total Sum:  {x.sum().item():.2f}")
print(f"Sum (Cols): {x.sum(dim=0)}")
print(f"Sum (Rows): {x.sum(dim=1)}\n")


Total Sum:  54.22
Sum (Cols): tensor([12.2970, 23.6914, 18.2327])
Sum (Rows): tensor([18.7754, 22.0978, 13.3479])



FInding the Means IN the Matrix


In [ ]:
# --- 2. MEAN (Average) ---
print(f"Total Mean:  {x.mean().item():.2f}")
print(f"Mean (Cols): {x.mean(dim=0)}")
print(f"Mean (Rows): {x.mean(dim=1)}\n")

Total Mean:  6.02
Mean (Cols): tensor([4.0990, 7.8971, 6.0776])
Mean (Rows): tensor([6.2585, 7.3659, 4.4493])



FInding the Min and the Max values


In [ ]:
# --- 3. MIN & MAX (Values) ---
print(f"Global Max: {x.max().item():.2f} | Global Min: {x.min().item():.2f}")
# .values is needed when using 'dim' with max/min
print(f"Max per Column: {x.max(dim=0).values}")
print(f"Max per Row:    {x.max(dim=1).values}\n")

Global Max: 8.87 | Global Min: 0.08
Max per Column: tensor([7.3380, 8.7319, 8.8727])
Max per Row:    tensor([8.7319, 8.8727, 6.6545])



To know about the Index of the mIn and max of the Min and the max value


In [ ]:
# --- 4. ARGMAX & ARGMIN (Positions) ---
# Tells you WHERE the largest/smallest numbers are located
print(f"Global Max Index: {x.argmax().item()}")
print(f"Max Index per Col: {x.argmax(dim=0)}")
print(f"Max Index per Row: {x.argmax(dim=1)}\n")


Global Max Index: 5
Max Index per Col: tensor([0, 0, 1])
Max Index per Row: tensor([1, 2, 2])



FInding Standard Deviation
# std: Standard Deviation. Tells you how "spread out" the numbers are from the mean.


In [ ]:
# --- 5. STD (Standard Deviation) ---
print(f"Global Std:  {x.std().item():.2f}")
print(f"Std (Cols): {x.std(dim=0)}")
print(f"Std (Rows): {x.std(dim=1)}\n")


Global Std:  2.98
Std (Cols): tensor([3.6900, 1.1299, 3.1239])
Std (Rows): tensor([3.1549, 2.1714, 3.7822])



finding Average


In [ ]:
# mean: The average of all numbers (Sum / Total number of elements).
print(f"Mean (Average): {x.mean().item():.2f}")

Mean (Average): 6.02


Mulitplicatin Along the COls and Rows and Of the FUll matrix

In [ ]:
# --- 6. PROD (Product / Multiplication) ---
print(f"Total Prod:  {x.prod().item():.2f}")
print(f"Prod (Cols): {x.prod(dim=0)}")
print(f"Prod (Rows): {x.prod(dim=1)}\n")

Total Prod:  225972.11
Prod (Cols): tensor([  2.9353, 481.9351, 159.7411])
Prod (Rows): tensor([173.3524, 361.2406,   3.6085])



ELement WIse OPeration


In [ ]:

# --- 7. ELEMENT-WISE (Apply to every single number) ---
print(f"Floor (Round Down): \n{torch.floor(x)}")
print(f"Ceil (Round Up):    \n{torch.ceil(x)}")
print(f"Clamp (Range 2-8):  \n{torch.clamp(x, 2, 8)}")

Floor (Round Down): 
tensor([[7., 8., 2.],
        [4., 8., 8.],
        [0., 6., 6.]])
Ceil (Round Up):    
tensor([[8., 9., 3.],
        [5., 9., 9.],
        [1., 7., 7.]])
Clamp (Range 2-8):  
tensor([[7.3380, 8.0000, 2.7055],
        [4.8770, 8.0000, 8.0000],
        [2.0000, 6.6114, 6.6545]])


Setting up matrix for the New OPerations

In [ ]:
# Setup matrices
m = torch.rand(3, 3) * 5
n = torch.rand(3, 3) * 5
print(f"Matrix m:\n{m}\nMatrix n:\n{n}\n")


Matrix m:
tensor([[1.2295, 1.2996, 0.9692],
        [1.3367, 1.4289, 2.8194],
        [0.8411, 0.3578, 0.8966]])
Matrix n:
tensor([[1.4509, 4.2247, 1.9519],
        [3.6678, 0.9273, 3.0333],
        [2.2076, 2.1038, 2.4395]])



FInding Transpose

In [ ]:

# Transpose means CHanging rows to Columns and COlumns to the Rows
print(f"Transpose: \n{torch.transpose(m, 0, 1)}")

Multiplying two Matrixes

In [ ]:
# Multiply two matrices (Matmul)
print(f"Multiply: \n{torch.matmul(m, n)}")

Multiply: 
tensor([[ 8.6900,  8.4384,  8.7062],
        [13.4044, 12.9036, 13.8214],
        [ 4.5119,  5.7713,  4.9142]])


Dot Product

In [ ]:
# Dot Product (Usually for vectors, but can do row-wise dot product like this):
dot_rows = torch.sum(m * n, dim=1)
print(f"Dot Product (Row-wise): {dot_rows}\n")

Dot Product (Row-wise): tensor([ 9.1659, 14.7799,  4.7967])



Finding Deerminant Matrix


In [ ]:

# Determinant & Inverse
print(f"Determinant: {torch.det(m)}")

Determinant: 1.1579136848449707


Finding Inverseo fthe Matrix

In [ ]:
print(f"Inverse: \n{torch.inverse(m)}\n")

Inverse: 
tensor([[ 0.2352, -0.7068,  1.9683],
        [ 1.0130,  0.2480, -1.8750],
        [-0.6249,  0.5641,  0.0170]])



Comparisons

In [ ]:

# --- 2. COMPARISONS (dim wise check) ---
# Greater/Less than/Equal to
print(f"Is m > n? \n{m > n}")
print(f"Any in Column > 4? {(m > 4).any(dim=0)}") # Column-wise
print(f"All in Row > 0?    {(m > 0).all(dim=1)}")  # Row-wise

Is m > n? 
tensor([[False, False, False],
        [False,  True, False],
        [False, False, False]])
Any in Column > 4? tensor([False, False, False])
All in Row > 0?    tensor([True, True, True])


FInding LOg
 Logarithm (log): Specifically the Natural Logarithm (base $e$). It answers the question: "To what power must we raise $e$ to get this number?"

In [ ]:
print(f"Log: {torch.log(m)}")

Log: tensor([[ 0.2066,  0.2620, -0.0313],
        [ 0.2902,  0.3569,  1.0365],
        [-0.1730, -1.0278, -0.1092]])


FInding Exponents (exp): Calculates $e$ (approx. 2.718) raised to the power of $x$. It is used to represent exponential growth in data.

In [ ]:
print(f"Exponents: {torch.exp(m)}")

Exponents: tensor([[ 3.4197,  3.6677,  2.6358],
        [ 3.8065,  4.1741, 16.7669],
        [ 2.3189,  1.4302,  2.4512]])



# Sqrt: The square root of each element.


In [ ]:
print(f"Sqrt: {torch.sqrt(m)}\n")

Sqrt: tensor([[1.1088, 1.1400, 0.9845],
        [1.1562, 1.1954, 1.6791],
        [0.9171, 0.5982, 0.9469]])



# Sigmoid: Squashes every number into a range between 0 and 1.
# Used to represent probabilities.

In [ ]:
print(f"Sigmoid: \n{torch.sigmoid(m)}")

Sigmoid: 
tensor([[0.7737, 0.7858, 0.7250],
        [0.7919, 0.8067, 0.9437],
        [0.6987, 0.5885, 0.7102]])


# Relu (Rectified Linear Unit): If a number is negative, it becomes 0.
# If it's positive, it stays the same. Very common in deep learning.

In [ ]:
# Relu (Rectified Linear Unit): If a number is negative, it becomes 0.
# If it's positive, it stays the same. Very common in deep learning.
print(f"Relu: \n{torch.relu(m)}")


Softmax

In [ ]:

# Softmax: Turns a vector of numbers into a probability distribution.
# All resulting numbers will be between 0 and 1, and their SUM will be exactly 1.
# - dim=0: Column-wise probability.
# - dim=1: Row-wise probability.
print(f"Softmax (Column-wise dim=0): \n{torch.softmax(m, dim=0)}")
print(f"Softmax (Row-wise dim=1):    \n{torch.softmax(m, dim=1)}\n")


Softmax (Column-wise dim=0): 
tensor([[0.3583, 0.3956, 0.1206],
        [0.3988, 0.4502, 0.7672],
        [0.2429, 0.1542, 0.1122]])
Softmax (Row-wise dim=1):    
tensor([[0.3517, 0.3772, 0.2711],
        [0.1538, 0.1687, 0.6775],
        [0.3740, 0.2307, 0.3953]])



INplace operations

In [ ]:
# --- 4. IN-PLACE OPERATIONS ---
# In-place: These operations modify the data directly in the original memory location.
# In PyTorch, these are identified by an underscore (_) at the end of the function name.
# Benefit: It saves memory because it doesn't create a copy of the tensor.
print("Applying In-place operations (modifies 'm' directly)...")
# add_: Adds matrix 'n' to 'm' and saves the result inside 'm'.
m.add_(n)
# relu_: Applies ReLU to 'm' and updates 'm' itself.
m.relu_()
print(f"Updated m (Original is now changed):\n{m}")

Applying In-place operations (modifies 'm' directly)...
Updated m (Original is now changed):
tensor([[2.6804, 5.5243, 2.9211],
        [5.0045, 2.3562, 5.8527],
        [3.0487, 2.4615, 3.3361]])


Cloning vs Copying


In [ ]:
import torch

print("--- SCENARIO 1: SIMPLE ASSIGNMENT (The 'Problem') ---")
original = torch.tensor([1, 2, 3])
copy_by_link = original  # b = a

print(f"Before change: Original = {original}, Copy = {copy_by_link}")

# We change the original tensor
original[0] = 99
print(f"After change:  Original = {original}, Copy = {copy_by_link}")
print("❌ PROBLEM: The copy changed too because they share the same memory!\n")


print("--- SCENARIO 2: CLONING (The 'Improvement') ---")
original = torch.tensor([1, 2, 3])
copy_by_clone = original.clone()  # b = a.clone()

print(f"Before change: Original = {original}, Clone = {copy_by_clone}")

# We change the original tensor
original[0] = 99
print(f"After change:  Original = {original}, Clone = {copy_by_clone}")
print("✅ SUCCESS: The clone stayed the same! It is a completely independent copy.\n")


# PROOF USING id()
print(f"ID of Original: {id(original)}")
print(f"ID of Link:     {id(copy_by_link)}  <-- Same as original")
print(f"ID of Clone:    {id(copy_by_clone)} <-- Different memory address")


--- SCENARIO 1: SIMPLE ASSIGNMENT (The 'Problem') ---
Before change: Original = tensor([1, 2, 3]), Copy = tensor([1, 2, 3])
After change:  Original = tensor([99,  2,  3]), Copy = tensor([99,  2,  3])
❌ PROBLEM: The copy changed too because they share the same memory!

--- SCENARIO 2: CLONING (The 'Improvement') ---
Before change: Original = tensor([1, 2, 3]), Clone = tensor([1, 2, 3])
After change:  Original = tensor([99,  2,  3]), Clone = tensor([1, 2, 3])
✅ SUCCESS: The clone stayed the same! It is a completely independent copy.

ID of Original: 135502338631360
ID of Link:     135496883979680  <-- Same as original
ID of Clone:    135496883977376 <-- Different memory address


Doing Operations on GPU

In [ ]:

# --- 2. GPU OPERATIONS ---
# First, check if a GPU (CUDA) is available, otherwise use CPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")
# Creating a new tensor directly on the GPU
# This is faster than creating it on CPU and moving it later.
tensor_on_gpu = torch.rand((2, 3), device=device)
print(f"Tensor on GPU:\n{tensor_on_gpu}\n")
# Moving an existing tensor from CPU to GPU
# .to(device) is the standard way to move data to your graphics card.
x = torch.tensor([10.0, 20.0]) # Created on CPU by default
x_gpu = x.to(device)           # Moved to GPU
print(f"Moved Tensor Device: {x_gpu.device}")

Using device: cuda
Tensor on GPU:
tensor([[0.6683, 0.8568, 0.6315],
        [0.3323, 0.0791, 0.0631]], device='cuda:0')

Moved Tensor Device: cuda:0


CPU vs GPU


In [ ]:
import torch
import time

# Matrix Size
size = 10000

# 1. CPU TEST
print(f"Testing CPU for size {size}x{size}...")
cpu_matrix = torch.rand(size, size)
start_cpu = time.time()
result_cpu = torch.matmul(cpu_matrix, cpu_matrix)
end_cpu = time.time()
cpu_duration = end_cpu - start_cpu
print(f"CPU Time: {cpu_duration:.4f} seconds")

# 2. GPU TEST (if available)
if torch.cuda.is_available():
    print(f"\nTesting GPU for size {size}x{size}...")
    device = torch.device("cuda")

    # Send data to GPU
    gpu_matrix = torch.rand(size, size, device=device)

    # Warm up the GPU (first run can be slow due to memory allocation)
    _ = torch.matmul(gpu_matrix, gpu_matrix)
    torch.cuda.synchronize()

    start_gpu = time.time()
    result_gpu = torch.matmul(gpu_matrix, gpu_matrix)
    torch.cuda.synchronize() # Must synchronize to wait for GPU to finish work!
    end_gpu = time.time()
    gpu_duration = end_gpu - start_gpu

    print(f"GPU Time: {gpu_duration:.4f} seconds")

    # --- SPEEDUP CALCULATION ---
    speedup = cpu_duration / gpu_duration
    print(f"\n--- RESULTS ---")
    print(f"The GPU was {speedup:.2f}x faster than the CPU!")

else:
    print("\nCUDA (GPU) not available on this system.")


Testing CPU for size 10000x10000...
CPU Time: 16.4346 seconds

Testing GPU for size 10000x10000...
GPU Time: 0.5782 seconds

--- RESULTS ---
The GPU was 28.42x faster than the CPU!


Reshaping, Squeezing, and NumPy

Flatten: Collapses all dimensions into one single 1D vector. Essential before passing data into a normal linear layer.
Permute: Changes the order of dimensions. Very common when converting images between different libraries (OpenCV vs PyTorch).
Unsqueeze: Adds a "fake" dimension of size 1. We use this to tell PyTorch: "This is a batch of 1 image."
Squeeze: The opposite of unsqueeze. It removes any dimension that has a size of 1 to simplify the shape.
NumPy Bridge (.numpy()): Converts the tensor to a NumPy array. Note: If the tensor is on GPU, you must call .cpu().numpy() because NumPy only runs on CPU.

In [ ]:
# --- RESHAPING ---
c = torch.rand(226, 226, 3) # Image-like tensor
print(f"Original Shape: {c.shape}")

# Flatten: Turns the whole matrix into one long 1D line of numbers
flattened = c.flatten()
print(f"Flattened Shape: {flattened.shape}")

# Permute: Reorders the dimensions (e.g., H, W, C -> C, H, W for PyTorch CNNs)
permuted = c.permute(2, 0, 1)
print(f"Permuted Shape: {permuted.shape}")

# Unsqueeze: Adds a new dimension of size 1 at index 0 (used for batching)
unsqueezed = c.unsqueeze(dim=0)
print(f"Unsqueezed Shape: {unsqueezed.shape}")

# Squeeze: Removes all '1s' from the shape
d = torch.rand(1, 10)
squeezed = d.squeeze()
print(f"Squeezed Shape: {squeezed.shape}\n")


# --- FROM TORCH TO NUMPY ---
# Use .numpy() to turn a PyTorch tensor back into a standard NumPy array
torch_tensor = torch.ones(5)
numpy_array = torch_tensor.numpy()
print(f"Object Type: {type(numpy_array)}")


Original Shape: torch.Size([226, 226, 3])
Flattened Shape: torch.Size([153228])
Permuted Shape: torch.Size([3, 226, 226])
Unsqueezed Shape: torch.Size([1, 226, 226, 3])
Squeezed Shape: torch.Size([10])

Object Type: <class 'numpy.ndarray'>


its 4th Lecture
Using the Git HUb profile here

In [ ]:

import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Football Dataset (Working Link)
url = 'https://raw.githubusercontent.com/martj42/international_results/master/results.csv'

# Load the data
df = pd.read_csv(url)

# Clean up empty columns
df = df.dropna(axis=1, how='all')

# Show the results
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False


Now will perform Further steps

In [ ]:
#print(df.info())
# Ya phir
#print(df.dtypes)
from sklearn.preprocessing import LabelEncoder, StandardScaler

# 1. Date ko handle karein (Ya toh drop kar dain ya numerical features nikalain)
# Filhal scaling ke liye drop kar dete hain kyunke date scale nahi hoti
df_clean = df.drop(columns=['date'])

# 2. Categorical columns ko numbers mein convert karein
le = LabelEncoder()
categorical_cols = ['home_team', 'away_team', 'tournament', 'city', 'country']

for col in categorical_cols:
    df_clean[col] = le.fit_transform(df_clean[col])

# 3. Handle Null Values (Aapke score columns mein missing values hain)
df_clean = df_clean.fillna(df_clean.mean())

# 4. Ab split karein
X_train, X_test, y_train, y_test = train_test_split(
    df_clean.iloc[:, 1:], # Features
    df_clean.iloc[:, 0],  # Target
    test_size=0.2,
    random_state=42
)

# 5. Ab scaling karein (Ab error nahi aayega!)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print("Preprocessing Done! X_train ab ready hai.")


Preprocessing Done! X_train ab ready hai.


preparing for computer readability

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

# 1. Data Load karein (Assuming 'df' is already loaded)
# df = pd.read_csv('your_file.csv')

# --- STEP 2: PREPROCESSING (Cleaning) ---
# Date column drop kar rahe hain kyunke ye scaling mein masla karti hai
if 'date' in df.columns:
    df = df.drop(columns=['date'])

# Missing values ko handle karna (float columns ke liye mean use kar rahe hain)
df = df.fillna(df.mean(numeric_only=True))

# --- STEP 3: ENCODING (Strings to Numbers) ---
# Target aur Features dono ko split se pehle encode kar rahe hain
# taake 'Unseen Labels' wala error na aaye.
le = LabelEncoder()

# Categorical columns ki list
categorical_cols = ['home_team', 'away_team', 'tournament', 'city', 'country']

for col in categorical_cols:
    if col in df.columns:
        df[col] = le.fit_transform(df[col].astype(str))

# Target column (Column index 0) ko bhi encode kar letay hain
df.iloc[:, 0] = le.fit_transform(df.iloc[:, 0].astype(str))

# --- STEP 4: TRAIN TEST SPLIT ---
# X = Features (Column 1 se end tak)
# y = Target (Column 0)
X = df.iloc[:, 1:]
y = df.iloc[:, 0]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# --- STEP 5: FEATURE SCALING ---
# Ab sab numbers hain, toh scaling smooth hogi
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
# Sirf target labels dekhne ke liye
y_train

# --- STEP 6: VERIFICATION ---
print("✅ Preprocessing Complete!")
print(f"X_train shape: {X_train.shape}")
print(f"Sample of scaled data:\n{X_train[:1]}")
# Is line ko replace karein
# print(y_train)

# Maan lo aapka column 0 'result' hai (Win/Loss)
# Isay sirf 0 aur 1 mein convert karne ke liye:
le_target = LabelEncoder()
y_train = le_target.fit_transform(y_train)

# Ab print karein
print(y_train)

✅ Preprocessing Complete!
X_train shape: (39429, 7)
Sample of scaled data:
[[-1.2582176   0.69996504 -0.84463353  0.74606476  1.42133425 -1.35868631
   1.66906852]]
[319 135 193 ...  92  28 170]


Numpy to pytorch

In [ ]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

# 1. Load working Football Data
url = 'https://raw.githubusercontent.com/martj42/international_results/master/results.csv'
df = pd.read_csv(url)

# 2. Preprocessing (Handling text columns)
# AI models need numbers, not team names
le = LabelEncoder()
df['home_team'] = le.fit_transform(df['home_team'])
df['away_team'] = le.fit_transform(df['away_team'])
df['tournament']=le.fit_transform(df['tournament'])


# 3. Define Features (X) and Target (y)
# Predict 'home_score' based on the teams playing
X = df[['home_team', 'away_team']].values  # .values makes it a numpy array immediately
y = df['home_score'].values

# 4. Split Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 5. Scale the Data (Standard Practice)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 6. FIXED: Convert to Tensors
# Since we used .values above, these are already numpy arrays
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()


X_train_tensor
print("✅ All steps completed successfully!")
print(f"Training data shape: {X_train_tensor.shape}")
print("Mubarakan Shoaib bhai! Data is ready for the Model.")

✅ All steps completed successfully!
Training data shape: torch.Size([39429, 2])
Mubarakan Shoaib bhai! Data is ready for the Model.


Defining Simpel Neural Network torch.optim provides optimization Algo During the Training of the our Neural network

In [ ]:
import torch
import numpy as np
import torch.nn as nn

# 1. Hyperparameters
learning_rate = 0.2
epochs = 100

# --- Data Preparation ---
if 'y_train' in locals():
    y_train_binary = (y_train > 0).astype(np.float32)
    y_train_tensor = torch.tensor(y_train_binary, dtype=torch.float32).view(-1, 1)
    X_train_tensor = torch.tensor(X_train, dtype=torch.float32)

    y_test_binary = (y_test > 0).astype(np.float32)
    y_test_tensor = torch.tensor(y_test_binary, dtype=torch.float32).view(-1, 1)
    X_test_tensor = torch.tensor(X_test, dtype=torch.float32)

# 2. Class Definition
class SimpleNeuralNetwork(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

# 3. Model Training
if 'X_train_tensor' in locals():
    num_features = X_train_tensor.shape[1]
    model = SimpleNeuralNetwork(num_features)

    # Built-in Binary Cross Entropy Loss
    criterion = nn.BCELoss()

    # NEW: Using torch.optim (SGD - Stochastic Gradient Descent)
    # model.parameters() batata hai optimizer ko ke kin cheezon (weights/bias) ko update karna hai
    optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

    print(f"Starting Training...")
    print("-" * 45)

    for epoch in range(epochs):

        # 1. Forward pass: Model output nikaal raha hai
        y_pred = model(X_train_tensor)

        # 2. Loss calculate: Prediction aur actual label ka farq
        loss = criterion(y_pred, y_train_tensor)

        # 3. Zero Gradients: Pichle loop ke gradients ko clear karna zaroori hai
        # Taake naye gradients purano mein add (accumulate) na hon
        optimizer.zero_grad()

        # 4. Backward pass: Gradients calculate ho rahey hain (Chain Rule)
        loss.backward()

        # 5. Parameters update: Ye line manual 'weight -= lr * grad' ka kaam kar rahi hai
        # Optimizer automatically weights aur biases ko update kar dega
        optimizer.step()

        # Status Update
        if (epoch + 1) % 10 == 0 or epoch == 0:
            with torch.no_grad():
                y_pred_class = (y_pred > 0.5).float()
                accuracy = (y_pred_class == y_train_tensor).float().mean()
            print(f'Epoch: {epoch + 1:3d} | Loss: {loss.item():.4f} | Accuracy: {accuracy.item():.4f}')

    print("-" * 45)
    print("✅ Training Complete!")

    # 4. Final Evaluation
    print("\n--- Final Test Accuracy ---")
    with torch.no_grad():
        test_probs = model(X_test_tensor)
        test_preds = (test_probs > 0.5).float()
        test_accuracy = (test_preds == y_test_tensor).float().mean()
        print(f"Accuracy: {test_accuracy.item()}")

else:
    print("❌ Error: Tensors not found.")

Starting Training...
---------------------------------------------
Epoch:   1 | Loss: 0.6806 | Accuracy: 0.5647
Epoch:  10 | Loss: 0.6071 | Accuracy: 0.7331
Epoch:  20 | Loss: 0.5751 | Accuracy: 0.7578
Epoch:  30 | Loss: 0.5626 | Accuracy: 0.7578
Epoch:  40 | Loss: 0.5575 | Accuracy: 0.7578
Epoch:  50 | Loss: 0.5553 | Accuracy: 0.7578
Epoch:  60 | Loss: 0.5543 | Accuracy: 0.7578
Epoch:  70 | Loss: 0.5539 | Accuracy: 0.7578
Epoch:  80 | Loss: 0.5537 | Accuracy: 0.7578
Epoch:  90 | Loss: 0.5536 | Accuracy: 0.7578
Epoch: 100 | Loss: 0.5535 | Accuracy: 0.7578
---------------------------------------------
✅ Training Complete!

--- Final Test Accuracy ---
Accuracy: 0.7574558854103088


In [ ]:
model.weights
model.bias

tensor([1.1311], requires_grad=True)

Its Day 5 And We will Learn ABout the torch.nn Our Agenda for Today is nn torch.optim module (Both) of them are the Built in MOdules


What is NN module in pytorch?
Built in library in the In the Coore Pytorch that Prvides the Wide Array of the classess nd the functions Abstrcats the Complexity of the Creating and the Training of the Neural Netwroks by offering pre built layers and the LOss functions and Activation Functions and And utility functions

#Creating Model class



In [3]:
import torch
import torch.nn as nn

# inheriting NN module class for the usage ELse We will not be able to use it
class Model(nn.Module):
    # its going to be A Neuron that Will Take the 5 inputs and Will Provide the Single Output Layer
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )

    # FIXED: This must be indented inside the class
    def forward(self, features):
        out = self.network(features)
        return out

# Creating the Data Sets for the Further use
features = torch.rand(10, 5)

# Creating the Object of the MOdel of Our Avaialable Data Set
model = Model(num_features=5)

# Calling Model for the Forward pass
# We can use here model.forward(features) But pytorch is Here to Avoid this
# Because Oytorch Says Avoid this SO Correc tway is Here in the below

# Data ko model se guzarein
output = model(features)

print(output)

tensor([[0.5186],
        [0.5207],
        [0.5058],
        [0.5129],
        [0.5255],
        [0.5070],
        [0.5054],
        [0.5093],
        [0.5248],
        [0.5084]], grad_fn=<SigmoidBackward0>)


In [ ]:
#Showing Model Weights Here
model.linear1.bias

Parameter containing:
tensor([ 0.0021, -0.0189, -0.2769], requires_grad=True)

Installing torch infor here

In [5]:
!pip install torchinfo

In [6]:
#Lets use the torch info here
from torchinfo import summary
summary(model, input_size=(10, 5))


Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

Now lets Work with the Hidden Layer

In [ ]:
#Now lets Find out the Weights
model.linear1.weight

Parameter containing:
tensor([[-0.4430,  0.0333,  0.2410,  0.1799,  0.1109],
        [-0.2720,  0.3896,  0.3336, -0.3972,  0.1036],
        [ 0.2013,  0.2462,  0.0258, -0.1640,  0.1438]], requires_grad=True)

its day 6 to be continue from here
Data sets and Data Loaders


Wy we need Data Sets And the Data Loaders


the flow is we use batch flow it means FOr the Traing of the Model We are using the Full Data Sets for the Training of the Data


Dataset: Acts as an organized storage box that knows how to fetch and prepare individual data items one by one.

DataLoader: Acts as a delivery service that bundles those items into "batches," shuffles them, and feeds them to the model efficiently.

Memory Management: We use batches because loading an entire dataset at once would crash your computer’s memory (RAM/GPU).

Faster Learning: Small batches allow the model to update its weights more frequently, helping it learn and converge much faster than looking at everything at once.

Mini-batch Gradient Descent,

The Concept: Instead of calculating the error for the entire dataset (Batch GD) or just one row (Stochastic GD), you find the middle ground. You take a small "mini-batch" (e.g., 32 or 64 samples).

The Update: You calculate the average error for that mini-batch and update the model's weights immediately.

The Advantage: It is the "Goldilocks" of training—it's faster than Batch GD because you don't wait for the whole dataset, and it's more stable than Stochastic GD because the average of 32 samples is more reliable than just one.

four main technical headaches you face if you try to feed data into a model manually

1. No standard interface for data
 2. No easy way to apply transformations
3. Shuffling and sampling
Batch management & Parallelization

Data Sets vs Data Loader classes

The Dataset and DataLoader Classes
Overview
Dataset and DataLoader are core abstractions in PyTorch that decouple how you define your data from how you efficiently iterate over it in training loops.

1. Dataset Class
The Dataset class is essentially a blueprint. When you create a custom Dataset, you decide how data is loaded and returned. It defines three main functions:

__init__(): Tells how the data should be loaded (e.g., reading a CSV file or listing image paths).

__len__(): Returns the total number of samples in the dataset.

__getitem__(index): Returns a single data point (and its label) at the specific given index.

2. DataLoader Class
The DataLoader wraps a Dataset and handles batching, shuffling, and parallel loading for you.

DataLoader Control Flow:
Shuffle: At the start of each epoch, the DataLoader shuffles the indices (if shuffle=True) using a sampler.

Batching: It divides the indices into chunks based on your defined batch size.

Parallel Loading: It uses background processes to load the next batch while the model is training.

Summary of the Visual Flow
Storage: The Raw Data (cylinder/database) is organized by the Dataset Class.

Structure: The Dataset Class uses len and getitem to make the data accessible.

Delivery: The DataLoader Class pulls from the Dataset to create the grid of batches used in the training loop.

Collate

In PyTorch, Collate (specifically the collate_fn) is the final step where individual data items are "glued" together to form a single batch.
Without Collate, the DataLoader would just give you a list of 32 separate things, but models only understand "Batches" (Tensors with a batch dimension)

In [3]:
from sklearn.datasets import make_classification
import torch

# Step 1: Create a synthetic classification dataset using sklearn
X, y = make_classification(
    n_samples=10,            # Number of samples
    n_features=2,           # Number of features
    n_informative=2,        # Number of informative features
    n_redundant=0,          # Number of redundant features
    n_classes=2,            # Number of classes
    random_state=42         # For reproducibility
)

In [4]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [5]:
X.shape


(10, 2)

Output column

In [7]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

convert to Tensors


In [8]:
X=torch.tensor(X,dtype=torch.float32)
y=torch.tensor(y,dtype=torch.float32)

In [9]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [10]:
y

tensor([1., 0., 0., 0., 0., 1., 1., 1., 1., 0.])

In [11]:
from torch.utils.data import Dataset,DataLoader


In [12]:
class CustomDataset(Dataset):
  def __init__(self,features,labels):
    self.features=features
    self.labels=labels

  def __len__(self):
    return self.features.shape[0]


  def __getitem__(self,index):
    return self.features[index],self.labels[index]






Object of Data Set

In [15]:
dataset=CustomDataset(X,y)

In [16]:
len(dataset)

10

In [18]:
dataset[4]

(tensor([-1.9629, -0.9923]), tensor(0.))

In [21]:
dataloader=DataLoader(dataset,batch_size=2,shuffle=True)

In [22]:
for batch_features, batch_labels in  dataloader:
  print(batch_features)
  print(batch_labels)
  print("_"*50)

tensor([[ 1.7774,  1.5116],
        [ 1.0683, -0.9701]])
tensor([1., 1.])
__________________________________________________
tensor([[-0.9382, -0.5430],
        [-1.9629, -0.9923]])
tensor([1., 0.])
__________________________________________________
tensor([[ 1.7273, -1.1858],
        [-0.5872, -1.9717]])
tensor([1., 0.])
__________________________________________________
tensor([[-0.7206, -0.9606],
        [-1.1402, -0.8388]])
tensor([0., 0.])
__________________________________________________
tensor([[-2.8954,  1.9769],
        [ 1.8997,  0.8344]])
tensor([0., 1.])
__________________________________________________


But if we do the Shuffle to the Off then We will Get the batches in an Order

A note about ParallelizationThe ScenarioImagine the entire data loading and training process for one epoch with num_workers=4.Assumptions:Total samples: 10,000Batch size: 32Workers (num_workers): 4Total Batches: Approximately 312 full batches per epoch ($10,000 / 32 \approx 312$).Workflow1. Sampler and Batch Creation (Main Process):Before training starts for the epoch, the DataLoader’s sampler generates a shuffled list of all 10,000 indices. These are then grouped into 312 batches of 32 indices each. All these batches are queued up, ready to be fetched by workers.2. Parallel Data Loading (Workers):At the start of the training epoch, you run a training loop like:Pythonfor batch_data, batch_labels in dataloader:
    # Training logic
Under the hood, as soon as you start iterating over the dataloader, it dispatches the first four batches of indices to the four workers:Worker #1 loads batch 1 (indices [batch_1_indices])Worker #2 loads batch 2 (indices [batch_2_indices])Worker #3 loads batch 3 (indices [batch_3_indices])Worker #4 loads batch 4 (indices [batch_4_indices])Each worker:Fetches the corresponding samples by calling __getitem__ on the dataset for each index in the batch.Applies any defined transforms and passes the samples through collate_fn to form a single batch tensor.3. First Batch Returned to Main Process:Whichever worker finishes first sends its fully prepared batch (e.g., batch 1) back to the main process.As soon as the main process gets this first prepared batch, it yields it to your training loop, so your code receives [batch_data, batch_labels] for the first batch.4. Model Training on the Main Process:(Text cuts off here, but implies the GPU/Main CPU starts training on the first batch while workers continue preparing the next ones.)

A note about samplers
In PyTorch, the sampler in the DataLoader determines the strategy for selecting samples from the dataset during data loading. It controls how indices of the dataset are drawn for each batch.

Types of Samplers
PyTorch provides several predefined samplers, and you can create custom ones:

1. SequentialSampler:
Samples elements sequentially, in the order they appear in the dataset (0, 1, 2, 3...).

This is the default when shuffle=False.

Best for: Validation or testing where the order doesn't matter or needs to be consistent.

2. RandomSampler:
Samples elements randomly without replacement.

This is the default when shuffle=True.

Best for: Training, because it prevents the model from learning the order of the data rather than the actual patterns.

A note about collate_fnThe collate_fn in PyTorch's DataLoader is a function that specifies how to combine a list of samples from a dataset into a single batch. By default, the DataLoader uses a simple batch collation mechanism, but collate_fn allows you to customize how the data should be processed and batched.Example Scenario: Variable Length SequencesThe table below shows why a default collation might fail. Notice that the sequences have different lengths:SentenceTokenized (Integer IDs)Label"I love coding"[1, 2, 3]0"Deep learning rocks"[4, 5, 6]1"Transformers are fun"[7, 8, 9, 10]1"Hello world"[11, 12]0

Important DataLoader Parameters
1. dataset (mandatory)
The Dataset from which the DataLoader will pull data.

Must be a subclass of torch.utils.data.Dataset that implements __getitem__ and __len__.

2. batch_size
How many samples per batch to load.

Default is 1.

Larger batch sizes can speed up training on GPUs but require more memory.

3. shuffle
If True, the DataLoader will shuffle the dataset indices each epoch.

Helpful to avoid the model becoming too dependent on the order of samples.

4. num_workers
The number of worker processes used to load data in parallel.

Setting num_workers > 0 can speed up data loading by leveraging multiple CPU cores, especially if I/O or preprocessing is a bottleneck.

5. pin_memory (Note: marked "GPU")
If True, the DataLoader will copy tensors into pinned (page-locked) memory before returning them.

This can improve GPU transfer speed and thus overall training throughput, particularly on CUDA systems.

6. drop_last
If True, the DataLoader will drop the last incomplete batch if the total number of samples is not divisible by the batch size.

Useful when exact batch sizes are required (for example, in some batch normalization scenarios).