<a href="https://colab.research.google.com/github/muhammadshoaib549/pytorch/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

2.10.0+cu128
GPU is available!
Using GPU: Tesla T4


In [ ]:
#this is for the Empty
a=torch.empty(2,3)
print(a)


tensor([[2.1715e-18, 2.3081e-12, 2.6302e+20],
        [6.1943e-04, 3.6022e-12, 6.9989e+22]])


In [ ]:
#Checking the Type
type (a)


torch.Tensor

In [ ]:
#this is for the Ones
torch.ones(2,3)


tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#this is for the Random Values
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [ ]:
# manual Seed
torch.manual_seed(100)
random_tensor = torch.rand(2, 3)
print(random_tensor)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


In [ ]:
#this is for the Tensor
# Fixed version
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# 4. Range and Distribution Functions
print("--- Specialized Initializers ---")

# arange: (start, end, step) -> excludes end
print("Using arange  ->", torch.arange(0, 10, 2))

# linspace: (start, end, steps) -> includes end
print("Using linspace ->", torch.linspace(0, 10, 10))

# eye: Identity Matrix (diagonal of 1s)
print("Using eye      ->\n", torch.eye(5))

# full: (shape, value) -> fills everything with the value
print("Using full     ->\n", torch.full((3, 3), 5))

--- Specialized Initializers ---
Using arange  -> tensor([0, 2, 4, 6, 8])
Using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eye      ->
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full     ->
 tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [ ]:
# Define x first
x = torch.tensor([[1, 2, 3], [4, 5, 6],[1,4,5]])

# Then run your checks
print(f"Shape: {x.shape}")
print(f"Rank (ndim): {x.ndim}")
print(f"Total elements: {x.numel()}")
print(f"Data type: {x.dtype}")
print(f"Device: {x.device}")


Shape: torch.Size([3, 3])
Rank (ndim): 2
Total elements: 9
Data type: torch.int64
Device: cpu


In [ ]:
#this is for the zero likes
torch.zeros_like(x)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [ ]:
#this is fr the ones like
torch.ones_like(x)


tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [ ]:
# Create a starting tensor
x = torch.tensor([[1, 0, 3], [4, 5, 6]], dtype=torch.int32)
#You are telling Python to take the string "-" and repeat it 30 times.
print(f"Original Tensor:\n{x}\n" + "-"*30)

# --- FLOATING POINT TYPES ---
# Standard for DL (float32), high precision (float64), and half-precision (float16/bfloat16)
x_f32 = x.to(torch.float32)
x_f64 = x.to(torch.float64)
x_f16 = x.to(torch.float16)
x_bf16 = x.to(torch.bfloat16)

# --- INTEGER TYPES ---
# 8-bit to 64-bit signed integers
x_i8 = x.to(torch.int8)
x_i16 = x.to(torch.int16)
x_i32 = x.to(torch.int32)
x_i64 = x.to(torch.int64)

# Unsigned 8-bit (commonly used for images)
x_uint8 = x.to(torch.uint8)

# --- BOOLEAN & COMPLEX ---
x_bool = x.to(torch.bool)        # 0 becomes False, non-zero becomes True
x_c64 = x.to(torch.complex64)    # Real numbers become the 'real' part of the complex num

# --- PRINTING THE RESULTS ---
types_to_show = [
    ("32-bit Float", x_f32),
    ("64-bit Float", x_f64),
    ("16-bit Float", x_f16),
    ("BFloat16", x_bf16),
    ("8-bit Int", x_i8),
    ("32-bit Int", x_i32),
    ("64-bit Int", x_i64),
    ("Unsigned Int8", x_uint8),
    ("Boolean", x_bool),
    ("Complex 64", x_c64)
]

for name, tensor in types_to_show:
    print(f"{name:15} | Dtype: {str(tensor.dtype):18} | Example Value: {tensor[0,0]}")

Original Tensor:
tensor([[1, 0, 3],
        [4, 5, 6]], dtype=torch.int32)
------------------------------
32-bit Float    | Dtype: torch.float32      | Example Value: 1.0
64-bit Float    | Dtype: torch.float64      | Example Value: 1.0
16-bit Float    | Dtype: torch.float16      | Example Value: 1.0
BFloat16        | Dtype: torch.bfloat16     | Example Value: 1.0
8-bit Int       | Dtype: torch.int8         | Example Value: 1
32-bit Int      | Dtype: torch.int32        | Example Value: 1
64-bit Int      | Dtype: torch.int64        | Example Value: 1
Unsigned Int8   | Dtype: torch.uint8        | Example Value: 1
Boolean         | Dtype: torch.bool         | Example Value: True
Complex 64      | Dtype: torch.complex64    | Example Value: (1+0j)


In [ ]:
# This is the line for the Generating Random Tensor Just matching like the X one

random_tensor = torch.rand_like(x, dtype=torch.float32)

print("Random Tensor (same shape as x):")
print(random_tensor)
print(f"New Dtype: {random_tensor.dtype}")

Random Tensor (same shape as x):
tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])
New Dtype: torch.float32


Mathematical OPerations

In [ ]:
import torch

# Create a random 2x2 tensor
x = torch.rand(2, 2)
print(f"Original x:\n{x}\n")

# --- Math Operations ---

# addition
print(f"Addition (x + 10):\n{x + 10}")

# substraction
print(f"Subtraction (x - 5):\n{x - 5}")

# multiplication
print(f"Multiplication (x * 2):\n{x * 2}")

# division
print(f"Division (x / 2):\n{x / 2}")

# int division (floor division)
print(f"Int Division (x // 0.5):\n{x // 0.5}")

# --- Power and Modulo ---

# Power (Exponentiation)
# Use ** to raise x to a power (e.g., x squared)
power_res = x ** 2
print(f"Power (x^2):\n{power_res}")

# Modulo (Remainder) logic from your snippet
# (x // 0.5) calculates how many 0.5s fit in x, then % 2 checks if that count is even/odd
logic_gate = (x // 0.5) % 2
print(f"Logic Gate ((x // 0.5) % 2):\n{logic_gate}")

Original x:
tensor([[0.9535, 0.7064],
        [0.1629, 0.8902]])

Addition (x + 10):
tensor([[10.9535, 10.7064],
        [10.1629, 10.8902]])
Subtraction (x - 5):
tensor([[-4.0465, -4.2936],
        [-4.8371, -4.1098]])
Multiplication (x * 2):
tensor([[1.9071, 1.4128],
        [0.3258, 1.7804]])
Division (x / 2):
tensor([[0.4768, 0.3532],
        [0.0814, 0.4451]])
Int Division (x // 0.5):
tensor([[1., 1.],
        [0., 1.]])
Power (x^2):
tensor([[0.9092, 0.4990],
        [0.0265, 0.7925]])
Logic Gate ((x // 0.5) % 2):
tensor([[1., 1.],
        [0., 1.]])


ElementWise


In [ ]:
# Create two random tensors of the same shape (2x3)
a = torch.rand(2, 3)
b = torch.rand(2, 3)

print("Tensor a:")
print(a)
print("\nTensor b:")
print(b)
print("-" * 30)

# 1. add
# Adds each element of a to the corresponding element of b
add_res = a + b
# Or: torch.add(a, b)

# 2. sub
# Subtracts b from a element-wise
sub_res = a - b
# Or: torch.sub(a, b)

# 3. multiply
# This is Hadamard Product (NOT matrix multiplication)
# It multiplies 0.0554 * 0.3466, etc.
mult_res = a * b
# Or: torch.mul(a, b)

# 4. division
# Divides a by b element-wise
div_res = a / b
# Or: torch.div(a, b)

# Display results
print(f"Addition Result:\n{add_res}")
print(f"Sub\n{sub_res}")
print(f"Devision\n{div_res}")
print(f"Multiplication Result:\n{mult_res}")

Tensor a:
tensor([[0.6017, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])

Tensor b:
tensor([[0.3079, 0.6269, 0.8277],
        [0.6594, 0.0887, 0.4890]])
------------------------------
Addition Result:
tensor([[0.9096, 1.0504, 1.3501],
        [1.0769, 0.1227, 1.4047]])
Sub
tensor([[ 0.2938, -0.2035, -0.3052],
        [-0.2418, -0.0547,  0.4268]])
Devision
tensor([[1.9541, 0.6754, 0.6312],
        [0.6332, 0.3834, 1.8728]])
Multiplication Result:
tensor([[0.1852, 0.2655, 0.4324],
        [0.2753, 0.0030, 0.4478]])


Video from 41 Some Operaations on the Single Tensor

In [4]:
c=torch.tensor([1,-2,3,-4])

In [5]:
#Absolute value
torch.abs(c)


tensor([1, 2, 3, 4])

In [6]:
#Convering to the Negative from the zero
torch.neg(c)


tensor([-1,  2, -3,  4])

In [7]:
#Rounding
torch.round(c)


tensor([ 1, -2,  3, -4])

Lets Leran About the Tensor Operations


In [4]:

# 1. Generate ONE random tensor (3x3)
# We multiply by 10 to make the floor/ceil/clamp operations more visible
x = torch.rand(3, 3) * 10
print(f"--- The Random Tensor ---\n{x}\n")


--- The Random Tensor ---
tensor([[7.3380, 8.7319, 2.7055],
        [4.8770, 8.3481, 8.8727],
        [0.0820, 6.6114, 6.6545]])



Lets Learn ABut the Some of the Reduce FUnctins


FLoor Fuction

In [5]:
# --- 1. ROUNDING OPERATIONS ---
# floor: Removes the decimal and rounds DOWN (e.g., 3.9 becomes 3)
print(f"Floor (Round Down): \n{torch.floor(x)}")

Floor (Round Down): 
tensor([[7., 8., 2.],
        [4., 8., 8.],
        [0., 6., 6.]])


Learning about the CELL


In [6]:

# ceil: Rounds UP to the next integer (e.g., 3.1 becomes 4)
print(f"Ceil (Round Up): \n{torch.ceil(x)}")

Ceil (Round Up): 
tensor([[8., 9., 3.],
        [5., 9., 9.],
        [1., 7., 7.]])


Lets Learn ABout the Clamp


In [7]:
# clamp: Limits values to a range.
# Anything smaller than 'min' becomes 'min'. Anything larger than 'max' becomes 'max'.
print(f"Clamp (Forcing values between 3.0 and 7.0): \n{torch.clamp(x, 3.0, 7.0)}\n")

Clamp (Forcing values between 3.0 and 7.0): 
tensor([[7.0000, 7.0000, 3.0000],
        [4.8770, 7.0000, 7.0000],
        [3.0000, 6.6114, 6.6545]])



FInding the SUm of the Matix ANd the Dimension WIse


In [8]:
# --- 1. SUM (Addition) ---
print(f"Total Sum:  {x.sum().item():.2f}")
print(f"Sum (Cols): {x.sum(dim=0)}")
print(f"Sum (Rows): {x.sum(dim=1)}\n")


Total Sum:  54.22
Sum (Cols): tensor([12.2970, 23.6914, 18.2327])
Sum (Rows): tensor([18.7754, 22.0978, 13.3479])



FInding the Means IN the Matrix


In [9]:
# --- 2. MEAN (Average) ---
print(f"Total Mean:  {x.mean().item():.2f}")
print(f"Mean (Cols): {x.mean(dim=0)}")
print(f"Mean (Rows): {x.mean(dim=1)}\n")

Total Mean:  6.02
Mean (Cols): tensor([4.0990, 7.8971, 6.0776])
Mean (Rows): tensor([6.2585, 7.3659, 4.4493])



FInding the Min and the Max values


In [10]:
# --- 3. MIN & MAX (Values) ---
print(f"Global Max: {x.max().item():.2f} | Global Min: {x.min().item():.2f}")
# .values is needed when using 'dim' with max/min
print(f"Max per Column: {x.max(dim=0).values}")
print(f"Max per Row:    {x.max(dim=1).values}\n")

Global Max: 8.87 | Global Min: 0.08
Max per Column: tensor([7.3380, 8.7319, 8.8727])
Max per Row:    tensor([8.7319, 8.8727, 6.6545])



To know about the Index of the mIn and max of the Min and the max value


In [11]:
# --- 4. ARGMAX & ARGMIN (Positions) ---
# Tells you WHERE the largest/smallest numbers are located
print(f"Global Max Index: {x.argmax().item()}")
print(f"Max Index per Col: {x.argmax(dim=0)}")
print(f"Max Index per Row: {x.argmax(dim=1)}\n")


Global Max Index: 5
Max Index per Col: tensor([0, 0, 1])
Max Index per Row: tensor([1, 2, 2])



FInding Standard Deviation
# std: Standard Deviation. Tells you how "spread out" the numbers are from the mean.


In [14]:
# --- 5. STD (Standard Deviation) ---
print(f"Global Std:  {x.std().item():.2f}")
print(f"Std (Cols): {x.std(dim=0)}")
print(f"Std (Rows): {x.std(dim=1)}\n")


Global Std:  2.98
Std (Cols): tensor([3.6900, 1.1299, 3.1239])
Std (Rows): tensor([3.1549, 2.1714, 3.7822])



finding Average


In [15]:
# mean: The average of all numbers (Sum / Total number of elements).
print(f"Mean (Average): {x.mean().item():.2f}")

Mean (Average): 6.02


Mulitplicatin Along the COls and Rows and Of the FUll matrix

In [16]:
# --- 6. PROD (Product / Multiplication) ---
print(f"Total Prod:  {x.prod().item():.2f}")
print(f"Prod (Cols): {x.prod(dim=0)}")
print(f"Prod (Rows): {x.prod(dim=1)}\n")

Total Prod:  225972.11
Prod (Cols): tensor([  2.9353, 481.9351, 159.7411])
Prod (Rows): tensor([173.3524, 361.2406,   3.6085])



ELement WIse OPeration


In [17]:

# --- 7. ELEMENT-WISE (Apply to every single number) ---
print(f"Floor (Round Down): \n{torch.floor(x)}")
print(f"Ceil (Round Up):    \n{torch.ceil(x)}")
print(f"Clamp (Range 2-8):  \n{torch.clamp(x, 2, 8)}")

Floor (Round Down): 
tensor([[7., 8., 2.],
        [4., 8., 8.],
        [0., 6., 6.]])
Ceil (Round Up):    
tensor([[8., 9., 3.],
        [5., 9., 9.],
        [1., 7., 7.]])
Clamp (Range 2-8):  
tensor([[7.3380, 8.0000, 2.7055],
        [4.8770, 8.0000, 8.0000],
        [2.0000, 6.6114, 6.6545]])


Setting up matrix for the New OPerations

In [18]:
# Setup matrices
m = torch.rand(3, 3) * 5
n = torch.rand(3, 3) * 5
print(f"Matrix m:\n{m}\nMatrix n:\n{n}\n")


Matrix m:
tensor([[1.2295, 1.2996, 0.9692],
        [1.3367, 1.4289, 2.8194],
        [0.8411, 0.3578, 0.8966]])
Matrix n:
tensor([[1.4509, 4.2247, 1.9519],
        [3.6678, 0.9273, 3.0333],
        [2.2076, 2.1038, 2.4395]])



FInding Transpose

In [ ]:

# Transpose means CHanging rows to Columns and COlumns to the Rows
print(f"Transpose: \n{torch.transpose(m, 0, 1)}")

Multiplying two Matrixes

In [19]:
# Multiply two matrices (Matmul)
print(f"Multiply: \n{torch.matmul(m, n)}")

Multiply: 
tensor([[ 8.6900,  8.4384,  8.7062],
        [13.4044, 12.9036, 13.8214],
        [ 4.5119,  5.7713,  4.9142]])


Dot Product

In [20]:
# Dot Product (Usually for vectors, but can do row-wise dot product like this):
dot_rows = torch.sum(m * n, dim=1)
print(f"Dot Product (Row-wise): {dot_rows}\n")

Dot Product (Row-wise): tensor([ 9.1659, 14.7799,  4.7967])



Finding Deerminant Matrix


In [21]:

# Determinant & Inverse
print(f"Determinant: {torch.det(m)}")

Determinant: 1.1579136848449707


Finding Inverseo fthe Matrix

In [22]:
print(f"Inverse: \n{torch.inverse(m)}\n")

Inverse: 
tensor([[ 0.2352, -0.7068,  1.9683],
        [ 1.0130,  0.2480, -1.8750],
        [-0.6249,  0.5641,  0.0170]])



Comparisons

In [23]:

# --- 2. COMPARISONS (dim wise check) ---
# Greater/Less than/Equal to
print(f"Is m > n? \n{m > n}")
print(f"Any in Column > 4? {(m > 4).any(dim=0)}") # Column-wise
print(f"All in Row > 0?    {(m > 0).all(dim=1)}")  # Row-wise

Is m > n? 
tensor([[False, False, False],
        [False,  True, False],
        [False, False, False]])
Any in Column > 4? tensor([False, False, False])
All in Row > 0?    tensor([True, True, True])


FInding LOg
 Logarithm (log): Specifically the Natural Logarithm (base $e$). It answers the question: "To what power must we raise $e$ to get this number?"

In [24]:
print(f"Log: {torch.log(m)}")

Log: tensor([[ 0.2066,  0.2620, -0.0313],
        [ 0.2902,  0.3569,  1.0365],
        [-0.1730, -1.0278, -0.1092]])


FInding Exponents (exp): Calculates $e$ (approx. 2.718) raised to the power of $x$. It is used to represent exponential growth in data.

In [25]:
print(f"Exponents: {torch.exp(m)}")

Exponents: tensor([[ 3.4197,  3.6677,  2.6358],
        [ 3.8065,  4.1741, 16.7669],
        [ 2.3189,  1.4302,  2.4512]])



# Sqrt: The square root of each element.


In [26]:
print(f"Sqrt: {torch.sqrt(m)}\n")

Sqrt: tensor([[1.1088, 1.1400, 0.9845],
        [1.1562, 1.1954, 1.6791],
        [0.9171, 0.5982, 0.9469]])



# Sigmoid: Squashes every number into a range between 0 and 1.
# Used to represent probabilities.

In [27]:
print(f"Sigmoid: \n{torch.sigmoid(m)}")

Sigmoid: 
tensor([[0.7737, 0.7858, 0.7250],
        [0.7919, 0.8067, 0.9437],
        [0.6987, 0.5885, 0.7102]])


# Relu (Rectified Linear Unit): If a number is negative, it becomes 0.
# If it's positive, it stays the same. Very common in deep learning.

In [ ]:
# Relu (Rectified Linear Unit): If a number is negative, it becomes 0.
# If it's positive, it stays the same. Very common in deep learning.
print(f"Relu: \n{torch.relu(m)}")


Softmax

In [28]:

# Softmax: Turns a vector of numbers into a probability distribution.
# All resulting numbers will be between 0 and 1, and their SUM will be exactly 1.
# - dim=0: Column-wise probability.
# - dim=1: Row-wise probability.
print(f"Softmax (Column-wise dim=0): \n{torch.softmax(m, dim=0)}")
print(f"Softmax (Row-wise dim=1):    \n{torch.softmax(m, dim=1)}\n")


Softmax (Column-wise dim=0): 
tensor([[0.3583, 0.3956, 0.1206],
        [0.3988, 0.4502, 0.7672],
        [0.2429, 0.1542, 0.1122]])
Softmax (Row-wise dim=1):    
tensor([[0.3517, 0.3772, 0.2711],
        [0.1538, 0.1687, 0.6775],
        [0.3740, 0.2307, 0.3953]])



INplace operations

In [29]:
# --- 4. IN-PLACE OPERATIONS ---
# In-place: These operations modify the data directly in the original memory location.
# In PyTorch, these are identified by an underscore (_) at the end of the function name.
# Benefit: It saves memory because it doesn't create a copy of the tensor.
print("Applying In-place operations (modifies 'm' directly)...")
# add_: Adds matrix 'n' to 'm' and saves the result inside 'm'.
m.add_(n)
# relu_: Applies ReLU to 'm' and updates 'm' itself.
m.relu_()
print(f"Updated m (Original is now changed):\n{m}")

Applying In-place operations (modifies 'm' directly)...
Updated m (Original is now changed):
tensor([[2.6804, 5.5243, 2.9211],
        [5.0045, 2.3562, 5.8527],
        [3.0487, 2.4615, 3.3361]])


Cloning vs Copying


In [30]:
import torch

print("--- SCENARIO 1: SIMPLE ASSIGNMENT (The 'Problem') ---")
original = torch.tensor([1, 2, 3])
copy_by_link = original  # b = a

print(f"Before change: Original = {original}, Copy = {copy_by_link}")

# We change the original tensor
original[0] = 99
print(f"After change:  Original = {original}, Copy = {copy_by_link}")
print("❌ PROBLEM: The copy changed too because they share the same memory!\n")


print("--- SCENARIO 2: CLONING (The 'Improvement') ---")
original = torch.tensor([1, 2, 3])
copy_by_clone = original.clone()  # b = a.clone()

print(f"Before change: Original = {original}, Clone = {copy_by_clone}")

# We change the original tensor
original[0] = 99
print(f"After change:  Original = {original}, Clone = {copy_by_clone}")
print("✅ SUCCESS: The clone stayed the same! It is a completely independent copy.\n")


# PROOF USING id()
print(f"ID of Original: {id(original)}")
print(f"ID of Link:     {id(copy_by_link)}  <-- Same as original")
print(f"ID of Clone:    {id(copy_by_clone)} <-- Different memory address")


--- SCENARIO 1: SIMPLE ASSIGNMENT (The 'Problem') ---
Before change: Original = tensor([1, 2, 3]), Copy = tensor([1, 2, 3])
After change:  Original = tensor([99,  2,  3]), Copy = tensor([99,  2,  3])
❌ PROBLEM: The copy changed too because they share the same memory!

--- SCENARIO 2: CLONING (The 'Improvement') ---
Before change: Original = tensor([1, 2, 3]), Clone = tensor([1, 2, 3])
After change:  Original = tensor([99,  2,  3]), Clone = tensor([1, 2, 3])
✅ SUCCESS: The clone stayed the same! It is a completely independent copy.

ID of Original: 135502338631360
ID of Link:     135496883979680  <-- Same as original
ID of Clone:    135496883977376 <-- Different memory address


Doing Operations on GPU

In [31]:

# --- 2. GPU OPERATIONS ---
# First, check if a GPU (CUDA) is available, otherwise use CPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")
# Creating a new tensor directly on the GPU
# This is faster than creating it on CPU and moving it later.
tensor_on_gpu = torch.rand((2, 3), device=device)
print(f"Tensor on GPU:\n{tensor_on_gpu}\n")
# Moving an existing tensor from CPU to GPU
# .to(device) is the standard way to move data to your graphics card.
x = torch.tensor([10.0, 20.0]) # Created on CPU by default
x_gpu = x.to(device)           # Moved to GPU
print(f"Moved Tensor Device: {x_gpu.device}")

Using device: cuda
Tensor on GPU:
tensor([[0.6683, 0.8568, 0.6315],
        [0.3323, 0.0791, 0.0631]], device='cuda:0')

Moved Tensor Device: cuda:0


CPU vs GPU


In [32]:
import torch
import time

# Matrix Size
size = 10000

# 1. CPU TEST
print(f"Testing CPU for size {size}x{size}...")
cpu_matrix = torch.rand(size, size)
start_cpu = time.time()
result_cpu = torch.matmul(cpu_matrix, cpu_matrix)
end_cpu = time.time()
cpu_duration = end_cpu - start_cpu
print(f"CPU Time: {cpu_duration:.4f} seconds")

# 2. GPU TEST (if available)
if torch.cuda.is_available():
    print(f"\nTesting GPU for size {size}x{size}...")
    device = torch.device("cuda")

    # Send data to GPU
    gpu_matrix = torch.rand(size, size, device=device)

    # Warm up the GPU (first run can be slow due to memory allocation)
    _ = torch.matmul(gpu_matrix, gpu_matrix)
    torch.cuda.synchronize()

    start_gpu = time.time()
    result_gpu = torch.matmul(gpu_matrix, gpu_matrix)
    torch.cuda.synchronize() # Must synchronize to wait for GPU to finish work!
    end_gpu = time.time()
    gpu_duration = end_gpu - start_gpu

    print(f"GPU Time: {gpu_duration:.4f} seconds")

    # --- SPEEDUP CALCULATION ---
    speedup = cpu_duration / gpu_duration
    print(f"\n--- RESULTS ---")
    print(f"The GPU was {speedup:.2f}x faster than the CPU!")

else:
    print("\nCUDA (GPU) not available on this system.")


Testing CPU for size 10000x10000...
CPU Time: 16.4346 seconds

Testing GPU for size 10000x10000...
GPU Time: 0.5782 seconds

--- RESULTS ---
The GPU was 28.42x faster than the CPU!


Reshaping, Squeezing, and NumPy

Flatten: Collapses all dimensions into one single 1D vector. Essential before passing data into a normal linear layer.
Permute: Changes the order of dimensions. Very common when converting images between different libraries (OpenCV vs PyTorch).
Unsqueeze: Adds a "fake" dimension of size 1. We use this to tell PyTorch: "This is a batch of 1 image."
Squeeze: The opposite of unsqueeze. It removes any dimension that has a size of 1 to simplify the shape.
NumPy Bridge (.numpy()): Converts the tensor to a NumPy array. Note: If the tensor is on GPU, you must call .cpu().numpy() because NumPy only runs on CPU.

In [33]:
# --- RESHAPING ---
c = torch.rand(226, 226, 3) # Image-like tensor
print(f"Original Shape: {c.shape}")

# Flatten: Turns the whole matrix into one long 1D line of numbers
flattened = c.flatten()
print(f"Flattened Shape: {flattened.shape}")

# Permute: Reorders the dimensions (e.g., H, W, C -> C, H, W for PyTorch CNNs)
permuted = c.permute(2, 0, 1)
print(f"Permuted Shape: {permuted.shape}")

# Unsqueeze: Adds a new dimension of size 1 at index 0 (used for batching)
unsqueezed = c.unsqueeze(dim=0)
print(f"Unsqueezed Shape: {unsqueezed.shape}")

# Squeeze: Removes all '1s' from the shape
d = torch.rand(1, 10)
squeezed = d.squeeze()
print(f"Squeezed Shape: {squeezed.shape}\n")


# --- FROM TORCH TO NUMPY ---
# Use .numpy() to turn a PyTorch tensor back into a standard NumPy array
torch_tensor = torch.ones(5)
numpy_array = torch_tensor.numpy()
print(f"Object Type: {type(numpy_array)}")


Original Shape: torch.Size([226, 226, 3])
Flattened Shape: torch.Size([153228])
Permuted Shape: torch.Size([3, 226, 226])
Unsqueezed Shape: torch.Size([1, 226, 226, 3])
Squeezed Shape: torch.Size([10])

Object Type: <class 'numpy.ndarray'>
